export const allYelpCategories = [
    { title: "Afghan" },
    { title: "African" },
    { title: "Senegalese" },
    { title: "South African" },
    { title: "American (New)" },
    { title: "American (Traditional)" },
    { title: "Arabian" },
    { title: "Argentine" },
    { title: "Armenian" },
    { title: "Asian Fusion" },
    { title: "Australian" },
    { title: "Austrian" },
    { title: "Bangladeshi" },
    { title: "Barbeque" },
    { title: "Basque" },
    { title: "Belgian" },
    { title: "Brasseries" },
    { title: "Brazilian" },
    { title: "Breakfast & Brunch" },
    { title: "Pancakes" },
    { title: "British" },
    { title: "Buffets" },
    { title: "Bulgarian" },
    { title: "Burgers" },
    { title: "Burmese" },
    { title: "Cafes" },
    { title: "Themed Cafes" },
    { title: "Cafeteria" },
    { title: "Cajun/Creole" },
    { title: "Cambodian" },
    { title: "Caribbean" },
    { title: "Dominican" },
    { title: "Haitian" },
    { title: "Puerto Rican" },
    { title: "Trinidadian" },
    { title: "Catalan" },
    { title: "Cheesesteaks" },
    { title: "Chicken Shop" },
    { title: "Chicken Wings" },
    { title: "Chinese" },
    { title: "Cantonese" },
    { title: "Dim Sum" },
    { title: "Hainan" },
    { title: "Shanghainese" },
    { title: "Szechuan" },
    { title: "Comfort Food" },
    { title: "Creperies" },
    { title: "Cuban" },
    { title: "Czech" },
    { title: "Delis" },
    { title: "Diners" },
    { title: "Dinner Theater" },
    { title: "Eritrean" },
    { title: "Ethiopian" },
    { title: "Fast Food" },
    { title: "Filipino" },
    { title: "Fish & Chips" },
    { title: "Fondue" },
    { title: "Food Court" },
    { title: "Food Stands" },
    { title: "French" },
    { title: "Mauritius" },
    { title: "Reunion" },
    { title: "Game Meat" },
    { title: "Gastropubs" },
    { title: "Georgian" },
    { title: "German" },
    { title: "Gluten-Free" },
    { title: "Greek" },
    { title: "Guamanian" },
    { title: "Halal" },
    { title: "Hawaiian" },
    { title: "Himalayan/Nepalese" },
    { title: "Honduran" },
    { title: "Hong Kong Style Cafe" },
    { title: "Hot Dogs" },
    { title: "Hot Pot" },
    { title: "Hungarian" },
    { title: "Iberian" },
    { title: "Indian" },
    { title: "Indonesian" },
    { title: "Irish" },
    { title: "Italian" },
    { title: "Calabrian" },
    { title: "Sardinian" },
    { title: "Sicilian" },
    { title: "Tuscan" },
    { title: "Japanese" },
    { title: "Conveyor Belt Sushi" },
    { title: "Izakaya" },
    { title: "Japanese Curry" },
    { title: "Ramen" },
    { title: "Teppanyaki" },
    { title: "Kebab" },
    { title: "Korean" },
    { title: "Kosher" },
    { title: "Laotian" },
    { title: "Latin American" },
    { title: "Colombian" },
    { title: "Salvadoran" },
    { title: "Venezuelan" },
    { title: "Live/Raw Food" },
    { title: "Malaysian" },
    { title: "Mediterranean" },
    { title: "Falafel" },
    { title: "Mexican" },
    { title: "Tacos" },
    { title: "Middle Eastern" },
    { title: "Egyptian" },
    { title: "Lebanese" },
    { title: "Modern European" },
    { title: "Mongolian" },
    { title: "Moroccan" },
    { title: "New Mexican Cuisine" },
    { title: "Nicaraguan" },
    { title: "Noodles" },
    { title: "Pakistani" },
    { title: "Pan Asia" },
    { title: "Persian/Iranian" },
    { title: "Peruvian" },
    { title: "Pizza" },
    { title: "Polish" },
    { title: "Polynesian" },
    { title: "Pop-Up Restaurants" },
    { title: "Portuguese" },
    { title: "Poutineries" },
    { title: "Russian" },
    { title: "Salad" },
    { title: "Sandwiches" },
    { title: "Scandinavian" },
    { title: "Scottish" },
    { title: "Seafood" },
    { title: "Singaporean" },
    { title: "Slovakian" },
    { title: "Somali" },
    { title: "Soul Food" },
    { title: "Soup" },
    { title: "Southern" },
    { title: "Spanish" },
    { title: "Sri Lankan" },
    { title: "Steakhouses" },
    { title: "Supper Clubs" },
    { title: "Sushi Bars" },
    { title: "Syrian" },
    { title: "Taiwanese" },
    { title: "Tapas Bars" },
    { title: "Tapas/Small Plates" },
    { title: "Tex-Mex" },
    { title: "Thai" },
    { title: "Turkish" },
    { title: "Ukrainian" },
    { title: "Uzbek" },
    { title: "Vegan" },
    { title: "Vegetarian" },
    { title: "Vietnamese" },
    { title: "Waffles" },
    { title: "Wraps" }
];